### ISSUE TITLE
BUG?: cannot change ssh port from group_vars

### ISSUE THREAD

**Issue by 749** [debops/ansible-sshd#65]
I tried setting the following in `ansible/inventory/group_vars/all/sshd.yml` so the port for ssh would be both 10000 and 22. I created a minimal debops project, running bootstrap first and then common on a fresh install of Ubuntu 24.04 in a VM.

```yaml
sshd__ports: ['10000', '22']
```

Unfortunately running this did not add/update the required `Port: 10000` line  in the `/etc/ssh/sshd_config` file.

only using the following actually changed the `sshd_config` file:

```yaml
---
sshd__configuration:
  - name: 'Port'
    raw: |
      {% for port in ['10000', '22'] %}
      {{ 'Port {}'.format(port) }}
      {% endfor %}
    state: "present"
```

If this is a known issue, please document it in https://docs.debops.org/en/master/ansible/roles/pam_access/getting-started.html so future users do not have to dig through the ansible scripts to understand this.
